#logging:
#  level:
#    root: DEBUG
spring:
  datasource:
    url: jdbc:h2:file:~/SLI0095.h2
    driverClassName: org.h2.Driver
    username: sa
    password: password
  thymleaf:
    cache: false
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
accessType: jdbc