spring:
  datasource:
    url: jdbc:h2:file:~/SLI0095.h2
    driverClassName: org.h2.Driver
    username: sa
    password:
  thymleaf:
    cache: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      generate-dll: true
      ddl-auto: create